### ISSUE TITLE
parse error: Invalid numeric literal at line 2, column 0

### ISSUE THREAD

**Issue by WC-william** [cbeley/beleyenv#5]
Not sure what's wrong but encountered this...

wc@penguin:~/.beleyenv/beleyenv$ ./index.sh
Hit:1 https://deb.debian.org/debian buster InRelease
Hit:2 https://security.debian.org/debian-security buster/updates InRelease
Ign:3 https://storage.googleapis.com/cros-packages/94 buster InRelease
Hit:4 https://storage.googleapis.com/cros-packages/94 buster Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
jq is already the newest version (1.5+dfsg-2+b1).
libnotify-bin is already the newest version (0.7.7-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
parse error: Invalid numeric literal at line 2, column 0

⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤
Beleyenv install failed!
⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤

**Comment by cbeley** [comment]
Not much has changed in a while, so this is a bit odd. It may have something to do with your environment. Unfortunately, I'm traveling extensively right now and can't dig too deeply, but if you could run the following and give me the output, I may be able to help you (or fix things if it's a bug):

bash -x ./index.sh

The main thing I need is what line and file it's referring to above that error, which bash -x should give us.

Other questions to help me debug:
1. Have you run beleyenv successfully before?
2. Are you running this on a clean install or have you already done things in the container? (the jq is already newest version message has my suspicious).
3. Are you using the official debian container on stable channel? (this is what you'll get if you do nothing but have chromeos install linux..you'll know if you did something else)
4. Double check config.json for typos/post the JSON into some sort of JSON validator -- random suspicion.

**Comment by WC-william** [comment]
Hi Chris,
Thanks for the quick response and my apologies for dragging you back to this. Hope you are enjoying your travel. I am also relatively new to the entire Chromeos x Linux platform. I have run the code but I still couldn't figure out anything with the return, the result as follows:

wc@penguin:~/.beleyenv/beleyenv$ bash -x ./index.sh
+ set -e
+ trap ctrlC INT
+ trap 'theEnd $?' EXIT
+ sudo apt update
Hit:1 https://deb.debian.org/debian buster InRelease                
Hit:2 https://security.debian.org/debian-security buster/updates InRelease
Ign:3 https://storage.googleapis.com/cros-packages/94 buster InRelease
Hit:4 https://storage.googleapis.com/cros-packages/94 buster Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
+ sudo apt-get -y install jq libnotify-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
jq is already the newest version (1.5+dfsg-2+b1).
libnotify-bin is already the newest version (0.7.7-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ ./configScripts/setup-ssh-keys.sh
parse error: Invalid numeric literal at line 2, column 0
+ theEnd 4
+ [[ 4 != \0 ]]
+ ./print.sh 'Beleyenv install failed!'

⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤
Beleyenv install failed!
⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤⬤

+ command -v notify-send
+ notify-send -a beleyenv 'beleyenv install failed!' 'You are probally now very sad.'


Regarding your questions:
1. This is my first time installing Beleyenv, and the first time installing on this device and on this build, which failed.
2. I have previously installed a few applications, including fcitx, android-tools-adb, Libreoffice, and snap, but I did not tamper with anything else further than installing these.
3. Yes, I am running the official debian container but on a beta channel, if that may be the issue?
4. I have double checked and validated the JSON.

**Comment by cbeley** [comment]
> Yes, I am running the official debian container but on a beta channel, if that may be the issue?
If you mean the beta channel of ChromeOS, I don't think so. If you switched the package channel of debian though, that's another story.

With what you gave me, I have two ideas:

1. Your config.json actually isn't valid after-all
2. You're using a newer version of jq -- which has some differences that would likely broke what I wrote in beleyenv.

It turns out the cryptic error you are getting is from jq -- it's effectively complaining that the JSON is invalid.

Let me know the output of `jq --version` and if you are comfortable with it, the contents of your config.json with anything sensitive censored out -- though please only censor sensitive characters and nothing else. Also, if you are missing 'email', it may cause this to happen.

**Comment by WC-william** [comment]
Thanks for the quick response again.

> If you mean the beta channel of ChromeOS, I don't think so. If you switched the package channel of debian though, that's another story.
I do mean the beta channel of ChromeOS. The Debian is exactly what comes with the chromeos, I have made no modifications.

The version of the jq:
`jq-1.5-1-a5b5cbe`

I did successfully validate the JSON with a few validation apps, but anything could happen. The content of config.json as follows:
{
    "email": "w********m@gmail.com",
    "name": "Will",
    "hosts": [],
    "dockerContexts": [],
    "sublimeLicense": null,
    "borgRepo": null,
    "installThingsWithEncryptedDeps": false
}

Thanks!

**Comment by cbeley** [comment]
Strange, I can't reproduce this and I see nothing wrong with the config you posted.

What happens if you just run the following within the beleyenv directory?

```
jq -r '.email' config.json
```

If that doesn't work (ie. it prints that same error), and considering it works for me with the sample you gave me and i'm on the exact same version of jq, I'd suspect two possibilities:

1. There is some sort of hidden character that is getting stripped out or ignored when you try to validate it or copy/paste it into github.
2. You have some smart quotes in your JSON that github is replacing or a validator is ignoring.

If the above fails, I'd expect the following command to also fail:

```
jq -r empty config.json
```

So, if the above is failing, try this: copy the sample config.json, and edit it without copying any text into it. Also be sure to use an editor actually designed for coding/plain text. I bet you it'll work. If you are curious to find the root cause, if you upload the actual file that fails directly somewhere, I can take a peek.


TEST: ““““““““ “
^ It doesn't look like github rewrites smart quotes, so not so sure there.

**Comment by cbeley** [comment]
It seems the issue is likely on your side. If I run into this, I'll re-open. If you can provide more info, feel free to re-open.

**Comment by cbeley** [comment]
Just a small update: today I did a completely fresh re-install and did not run into any issues that would have impacted you like you described. I already closed this, but just following up.

There was a small bug around the kitty install, but it still would have worked. That's already been pushed.
